----- Begin Fatal Exception 29-Sep-2023 16:07:22 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing the python configuration file named makeAnalysis.py
Exception Message:
A std::exception was thrown.
File "makeAnalysis.py" could not be opened!
----- End Fatal Exception -------------------------------------------------
